spring.application.name=clientes
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/db_clientes
# Aqui usamos placeholders. Se não houver valor local, ele usa o padrão após os ':'
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ATENÇÃO: Aqui NÃO tem valor padrão, o Spring vai exigir que esteja no application-local
jwt.secret=${JWT_SECRET}
springdoc.swagger-ui.path=/swagger-ui.html